# ##### Table names
# Grk_UGNT_BibleWord
# Hin_4_BibleWord
# Mal_4_BibleWord


curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"mat\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:mat"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"mrk\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:mrk"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"luk\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:luk"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"jhn\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:jhn"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"act\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:act"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"rom\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:rom"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"1co\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:1co"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"2co\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:2co"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"gal\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:gal"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"eph\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:eph"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"php\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:php"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"col\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:col"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"1th\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:1th"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"2th\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:2th"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"1ti\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:1ti"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"2ti\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:2ti"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"tit\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:tit"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"phm\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:phm"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"heb\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:heb"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"jas\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:jas"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"1pe\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:1pe"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"2pe\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:2pe"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"1jn\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:1jn"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"2jn\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:2jn"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"3jn\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:3jn"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"jud\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
echo "done one more book:jud"
curl -X POST "http://127.0.0.1:7000/bibles" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"bookcode\":\"rev\",\"tablename\":\"Grk_UGNT_BibleWord\"}"
